### ISSUE TITLE
Add 406 response to each schema.

### ISSUE THREAD

**Issue by mkettrick** [openconnectivityfoundation/cloud-services#10]
Per the spec: "If the recipient of a request cannot provide a response that is encoded according to the content of the Accept header, then a HTTP 406 (not acceptable) response shall be sent."

We need to add a 406 response to each of the schemas.

**Comment by WAvdBeek** [comment]
not sure if we have to do that.
i think it is better to remove the shall, since all other schemas and specs referencing issues do not specify the specific error code.

**Comment by mkettrick** [comment]
Note that there are many shall statements besides this one related to specific error codes.  So we should either change them all to something other than shall or keep them as they are and test them.

**Comment by WAvdBeek** [comment]
then we need to have a OCF wide action to clean it up.
it is very hard to make sure that the specific error code is send.
this is due to that code will follow a set of checks and if the first check fails it can return that error code.
regardless if there is a shall on a specific case.

**Comment by marktrayer** [comment]
Reasonable comment; we do avoid being explicit on final responses as you cannot actually guarantee that's what you'll get back ... for example in the 406 case you for an Accept you can't handle you may get a 400 because of some other issue or a 403 because your token has issues ... it all depends on where in a stack implementation the first error is handled/caught.  I'll update the spec using verbiage similar to how we handle this in the Core Spec.

**Comment by ondrejtomcik** [comment]
Closing issue, no action item on the schema.

**Comment by mkettrick** [comment]
Actually, there is an action here.  The latest version of the C2C spec allows a 406 error response but 406 is not called out as an allowed response in the schema:

        "responses": {
          "201": {
            "$ref": "#/definitions/SubscribeResponse"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          }
        },

This issue has been closed. Should I open a new one?
