### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by mkettrick** [openconnectivityfoundation/cloud-services#4]
This is a very long schema so it's going to take some time to digest fully.  At quick glace, I have two comments.

There are a few references that point to Ondrej's account.  Are these correct:

"$ref": "https://raw.githubusercontent.com/ondrejtomcik/coreocf/Bugzilla-2709/swagger2.0/oic.wk.d.swagger.json#/definitions/Device"

+++++++++++++++

In the examples, why don't the "links" show "if" and "p":

            "href": "/oic/d",
            "rt": [
              "oic.wk.d"
            ]

**Comment by marktrayer** [comment]
The required missing links parameters are just an oversight.  We can fix that.

**Comment by ondrejtomcik** [comment]
Only `href,` `rt` and `if` are required. Those are already added.
