### ISSUE TITLE
SubscribeRequest example won't pass schema validation

### ISSUE THREAD

**Issue by mkettrick** [openconnectivityfoundation/cloud-services#5]
From the schema:

      "required": [
        "eventsUrl",
        "eventTypes",
        "signingSecret"
      ],
      "example": {
        "eventsUrl": "https://events.example.com/",
        "eventTypes": [
          "devices_registered",
          "devices_unregistered"
        ]
      }

"signingSecret" is a mandatory Property so it should be included in the example.

**Comment by ondrejtomcik** [comment]
Resolved, signingSecret added to the example.
