### ISSUE TITLE
Resource Update and Resource Retrieve examples look odd

### ISSUE THREAD

**Issue by mkettrick** [openconnectivityfoundation/cloud-services#6]
The example for both schemas is this:

    "example": "o29kZXNpcmVkSHVtaWRpdHkYPGV0eXBlc4Fub2ljLnIuaHVtaWRpdHloaHVtaWRpdHkYKA=="

There is no key-value pair like I would expect (e.g. "temperature": 10.0).

**Comment by ondrejtomcik** [comment]
It's not odd.  It's valid CBOR.

**Comment by mkettrick** [comment]
None of the other examples use text like this that is not human readable. Can the following be changed in any way so that it provides something that would help a human understand the example?


    "ResourceUpdateRequest": {
      "type": "string",
      "description": "Desired content of the resource",
      "example": "o29kZXNpcmVkSHVtaWRpdHkYPGV0eXBlc4Fub2ljLnIuaHVtaWRpdHloaHVtaWRpdHkYKA=="
    },

**Comment by marktrayer** [comment]
The spec notes that content received by the cloud is passed through.  Thus CBOR in, CBOR out.  I'm ok with stating in the description that this is a CBOR encoded payload to add clarity.  We don't decode other properties that by their definition are not human readable either.

**Comment by ondrejtomcik** [comment]
Added to the description of the content.
