### ISSUE TITLE
Schema uses "event" instead of "notification" in many places

### ISSUE THREAD

**Issue by mkettrick** [openconnectivityfoundation/cloud-services#8]
As an example from "/api/v1/devices/{deviceId}/subscriptions":

"description": "Subscribe to device events by providing `eventTypes` you're interested in and `eventsUrl` API Endpoint where **_events_** will be sent to as defined. Successful response contains `subscriptionId` which identifies registered subscription and is part of each **_event_**. First **_event_** for each registered event type is received immediately after subscription and contains actual state of the resource, followed by new **_events_** in case of any change.

The schema needs to be scrubbed for misuse of "event".

**Comment by ondrejtomcik** [comment]
Updated, thanks.
